<div class="news-popup news-popup-active">
    <div class="container">
        <div class="row justify-content-between no-gutters">
            <div class="col-11 col-md-9">
                <p>
                    <span class="alert-message d-inline-block font-weight-bold px-3 py-2">
                        <?php echo $block->getButton() ?>
                    </span>
                </p>
                <p>
                    <?php echo $block->getText()?>

                </p>
            </div>
            <div class="col-1 col-md-auto text-right">
                <button type="button" class="btn btn-link btn-close inside-stroke-white-popup display-5">×</button>
            </div>
        </div>
    </div>
</div>
