<div class="text-banner-wrapper px-4 mx-md-0 text-center bg-theme-gray py-2">
    <span class="d-block font-size-18">
        <?php echo $block->getData('contentnew'); ?>
    </span>
</div>
<?php echo print_r($block->getData('display_from'),true); ?>


<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="https://www.sono.no/media/wysiwyg/Slide/Desktop/xKampanje_okt_bannner.jpeg.pagespeed.ic.kH_M8L6w20.webp" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://www.sono.no/media/wysiwyg/Slide/Desktop/Ergobjorn.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://www.sono.no/media/wysiwyg/Slide/Desktop/Hjemmekontor.jpg" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
